[Niava-Serial-Ports]
sendingPort = "port2"
receivingPort = "port2"  # or "port2" "port3"if different
MaxListeners=10

[port1]
serialport = "COM9"
serialbaud = 115200
databits = 8
parity = "none"
stopbits = 1
enabled = true

[port2]
serialport = "COM10"
serialbaud = 115200
databits = 8
parity = "none"
stopbits = 1
enabled = true

[port3]
serialport = "COM111"
serialbaud = 115200
databits = 8
parity = "none"
stopbits = 1
enabled = true
